### ISSUE TITLE
map is not working 

### ISSUE THREAD

**Issue by NitinMadhukar** [effe-iiita/Effe20-beta#7]

**Comment by sggts04** [comment]
aise kaise

**Comment by sggts04** [comment]
send ss
not working on phone or laptop?
if on laptop, were you running a server or directly opened the html file?
@NitinMadhukar

**Comment by NitinMadhukar** [comment]
its working on local server only

**Comment by sggts04** [comment]
ha dekha, karta hu try

**Comment by sggts04** [comment]
@NitinMadhukar should be working now, check karke close kardena agar chaljaye
